[window]
opacity = 0.35
blur = true

[font]
normal = { family = "monospace", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12.0

[colors]

